name: Build and Deploy Zola Site to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Set up Zola
        run: |
          curl -s -L https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

      - name: Build site with Zola
        run: |
          zola build

      - name: Deploy to GitHub Pages
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages  # Branch to deploy to GitHub Pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token for authentication

